# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install: cd Example && pod install && cd -
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild test -workspace Example/RandomUser.xcworkspace -scheme "RandomUser-Example" -destination "platform=iOS Simulator,OS=7.1,name=iPhone 5" ONLY_ACTIVE_ARCH=NO | xcpretty -c
